[package]
name = "drg_mod_integration"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.69"
async-trait = "0.1.64"
clap = { version = "4.1.6", features = ["derive"] }
dotenvy = "0.15.6"
futures = "0.3.26"
hex = "0.4.3"
inventory = "0.3.4"
lazy_static = "1.4.0"
modio = { version = "0.7.1", features = ["rustls-tls"] }
regex = "1.7.1"
repak = { git = "https://github.com/trumank/repak.git", version = "0.1.3" }
reqwest = { version = "0.11.14", features = ["blocking"] }
reqwest-middleware = "0.2.0"
serde = { version = "1.0.155", features = ["derive"] }
serde_json = "1.0.94"
sha2 = "0.10.6"
steamlocate = { git = "https://github.com/CosmicHorrorDev/steamlocate-rs.git", branch = "fully-switch-from-steamy-vdf" }
task-local-extensions = "0.1.3"
thiserror = "1.0.39"
tokio = { version = "1.25.0", features = ["full"] }
typetag = "0.2.6"
uesave = { git = "https://github.com/trumank/uesave-rs.git", version = "0.2.0" }
unreal_asset = { git = "https://github.com/AstroTechies/unrealmodding.git", version = "0.1.12" }
url = "2.3.1"
zip = { version = "0.6.4", default-features = false, features = ["aes-crypto", "deflate", "time"] }

[patch.crates-io]
modio = { git = "https://github.com/trumank/modio-rs.git", branch = "dev" }
