[package]
name = "hook"
repository.workspace = true
authors.workspace = true
license.workspace = true
version.workspace = true
edition.workspace = true

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
anyhow.workspace = true
repak.workspace = true
serde.workspace = true
serde_json.workspace = true
postcard.workspace = true
fs-err.workspace = true
tracing.workspace = true
patternsleuth = { workspace = true, features = ["process-internal", "image-pe"] }
retour = { version = "0.3.1", features = ["static-detour"] }
hook_resolvers = { path = "../hook_resolvers" }
windows = { version = "0.52.0", features = [
  "Win32_Foundation",
  "Win32_System_SystemServices",
  "Win32_System_LibraryLoader",
  "Win32_System_Memory",
  "Win32_System_Threading",
] }
mint_lib = { path = "../mint_lib" }
bitflags = "2.4.1"
widestring = "1.0.2"
