[package]
name = "hook"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.75"
patternsleuth = { git = "https://github.com/trumank/patternsleuth", features = ["process-internal"] }
retour = { version = "0.3.1", features = ["static-detour"] }
windows = { version = "0.52.0", features = [
  "Win32_Foundation",
  "Win32_System_SystemServices",
  "Win32_System_LibraryLoader",
  "Win32_System_Memory",
  "Win32_System_Threading",
] }
