[package]
name = "hook"
version = "0.1.0"
edition = "2021"

[lib]
#target = "x86_64-pc-windows-gnu"
name = "x3daudio1_7"
crate-type = ["cdylib"]

[dependencies]
memchr = "2.5.0"
winapi = "0.3.9"
windows = { version = "0.48.0", features = [
  "Win32_Foundation",
  "Win32_System_SystemServices",
  "Win32_UI_WindowsAndMessaging",
  "Win32_System_LibraryLoader",
  "Win32_System_Memory",
  "Win32_System_Threading",
  "Win32_Security",
  "Win32_System_ProcessStatus",
] }
